name: Build so‑NDKBuild
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c

      - name: Build
        run: $ANDROID_NDK/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk

      - name: Upload so
        uses: actions/upload-artifact@v4
        with:
          name: libdrmhook‑ndk
          path: libs/arm64-v8a/libdrmhook.so
